extends RefCounted

const TREE := {
	"class_id": "fighter",
	"start_node_id": "fighter_start",
	"starter_active_family": "cleave",
	"regions": [
		{"id": "start_core", "name": "Start / Core Fighter", "theme": "Core martial basics and frontline identity", "node_ids": ["fighter_start", "cleave_1", "heavy_grip", "iron_lungs", "forward_step", "brace", "measured_guard", "battle_frame", "forged_body", "seasoned_combatant"], "cluster_ids": ["battle_frame_ring", "warriors_habit"], "entry_node_ids": ["fighter_start"], "exit_node_ids": ["heavy_grip", "iron_lungs", "brace", "measured_guard"]},
		{"id": "crusher_offense", "name": "Crusher Offense", "theme": "Strength and heavy melee pressure", "node_ids": ["bonebreaker", "cleave_2", "stomp_1", "execution_stance"], "cluster_ids": [], "entry_node_ids": ["heavy_grip"], "exit_node_ids": ["execution_stance"]},
		{"id": "bulwark_defense", "name": "Bulwark Defense", "theme": "Block and survivability", "node_ids": ["wall_of_iron", "shield_bash_1", "iron_wall", "unbroken"], "cluster_ids": [], "entry_node_ids": ["iron_lungs", "brace"], "exit_node_ids": ["iron_wall", "unbroken"]},
		{"id": "weaponmaster_discipline", "name": "Weaponmaster Discipline", "theme": "Parry and martial technique", "node_ids": ["steel_timing", "parry_strike_1", "counterlord"], "cluster_ids": [], "entry_node_ids": ["measured_guard"], "exit_node_ids": ["counterlord"]},
		{"id": "warpath_aggression", "name": "Warpath Aggression", "theme": "Momentum and forward pressure", "node_ids": ["forward_pressure", "charge_1", "warpath_oath"], "cluster_ids": [], "entry_node_ids": ["forward_step"], "exit_node_ids": ["warpath_oath"]}
	],
	"clusters": [
		{"id": "battle_frame_ring", "region_id": "start_core", "name": "Battle Frame", "outer_node_ids": ["fighter_start", "cleave_1", "heavy_grip", "iron_lungs", "brace", "battle_frame"], "center_node_id": "forged_body", "completion_rule": "all_outer_nodes"},
		{"id": "warriors_habit", "region_id": "start_core", "name": "Warrior's Habit", "outer_node_ids": ["fighter_start", "heavy_grip", "iron_lungs", "forward_step", "measured_guard", "battle_frame"], "center_node_id": "seasoned_combatant", "completion_rule": "all_outer_nodes"}
	],
	"nodes": {
		"fighter_start": {"name": "Fighter Start", "region_id": "start_core", "type": "start", "unlock_rule": "always", "connections": ["heavy_grip", "iron_lungs", "brace", "cleave_1"], "cost": 0, "effects": {"strength": 1, "stamina": 1}, "ui_text": "Begin as a Fighter."},
		"cleave_1": {"name": "Cleave I", "region_id": "start_core", "type": "active_unlock", "unlock_rule": "adjacent", "skill_family": "cleave", "skill_tier": 1, "connections": ["fighter_start", "battle_frame"], "cost": 1, "effects": {"melee_damage": 4}, "ui_text": "Unlock Cleave."},
		"heavy_grip": {"name": "Heavy Grip", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["fighter_start", "bonebreaker", "forged_body", "seasoned_combatant"], "cost": 1, "effects": {"strength": 1, "melee_damage": 3}, "ui_text": "Gain Strength and Melee Damage."},
		"iron_lungs": {"name": "Iron Lungs", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["fighter_start", "wall_of_iron", "forged_body", "seasoned_combatant"], "cost": 1, "effects": {"stamina": 1, "max_health": 6}, "ui_text": "Gain Stamina and Health."},
		"forward_step": {"name": "Forward Step", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["battle_frame", "forward_pressure", "seasoned_combatant"], "cost": 1, "effects": {"run_speed": 2}, "ui_text": "Improve Run Speed."},
		"brace": {"name": "Brace", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["fighter_start", "measured_guard", "wall_of_iron", "forged_body"], "cost": 1, "effects": {"block": 2}, "ui_text": "Improve Block."},
		"measured_guard": {"name": "Measured Guard", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["brace", "steel_timing", "seasoned_combatant"], "cost": 1, "effects": {"parry": 2}, "ui_text": "Improve Parry."},
		"battle_frame": {"name": "Battle Frame", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["cleave_1", "forward_step", "forged_body", "seasoned_combatant"], "cost": 1, "effects": {"defense": 3, "max_health": 6}, "ui_text": "Gain Defense and Health."},
		"forged_body": {"name": "Forged Body", "region_id": "start_core", "type": "cluster_center", "unlock_rule": "cluster_complete", "cluster_id": "battle_frame_ring", "connections": [], "cost": 1, "effects": {"stamina": 2, "defense": 6, "max_health": 12}, "ui_text": "Unlock by completing the Battle Frame ring."},
		"seasoned_combatant": {"name": "Seasoned Combatant", "region_id": "start_core", "type": "cluster_center", "unlock_rule": "cluster_complete", "cluster_id": "warriors_habit", "connections": [], "cost": 1, "effects": {"strength": 2, "parry": 3, "run_speed": 2}, "ui_text": "Unlock by completing the Warrior's Habit ring."},
		"bonebreaker": {"name": "Bonebreaker", "region_id": "crusher_offense", "type": "passive_notable", "unlock_rule": "adjacent", "connections": ["heavy_grip", "cleave_2", "stomp_1"], "cost": 1, "effects": {"strength": 1, "melee_damage": 8}, "ui_text": "Gain heavy melee offense."},
		"cleave_2": {"name": "Cleave II", "region_id": "crusher_offense", "type": "active_upgrade", "unlock_rule": "adjacent", "skill_family": "cleave", "skill_tier": 2, "connections": ["bonebreaker", "execution_stance"], "cost": 1, "effects": {"melee_damage": 6}, "ui_text": "Upgrade Cleave."},
		"stomp_1": {"name": "Stomp I", "region_id": "crusher_offense", "type": "active_unlock", "unlock_rule": "adjacent", "skill_family": "stomp", "skill_tier": 1, "connections": ["bonebreaker"], "cost": 1, "effects": {"melee_damage": 5, "two_hand_damage": 4}, "ui_text": "Unlock Stomp."},
		"execution_stance": {"name": "Execution Stance", "region_id": "crusher_offense", "type": "keystone", "unlock_rule": "adjacent", "connections": ["cleave_2"], "cost": 1, "effects": {"melee_damage": 14, "block": -3}, "ui_text": "Trade defense for brutal offense."},
		"wall_of_iron": {"name": "Wall of Iron", "region_id": "bulwark_defense", "type": "passive_notable", "unlock_rule": "adjacent", "connections": ["iron_lungs", "brace", "shield_bash_1", "iron_wall"], "cost": 1, "effects": {"block": 5, "defense": 4}, "ui_text": "Bolster your defensive wall."},
		"shield_bash_1": {"name": "Shield Bash I", "region_id": "bulwark_defense", "type": "active_unlock", "unlock_rule": "adjacent", "skill_family": "shield_bash", "skill_tier": 1, "connections": ["wall_of_iron", "unbroken"], "cost": 1, "effects": {"block": 4, "melee_damage": 3}, "ui_text": "Unlock Shield Bash."},
		"iron_wall": {"name": "Iron Wall", "region_id": "bulwark_defense", "type": "keystone", "unlock_rule": "adjacent", "connections": ["wall_of_iron"], "cost": 1, "effects": {"block": 10, "defense": 6, "run_speed": -2}, "ui_text": "Become a stronger bulwark."},
		"unbroken": {"name": "Unbroken", "region_id": "bulwark_defense", "type": "keystone", "unlock_rule": "adjacent", "connections": ["shield_bash_1"], "cost": 1, "effects": {"stamina": 1, "health_regen": 6, "attack_speed": -2}, "ui_text": "Greatly improve staying power."},
		"steel_timing": {"name": "Steel Timing", "region_id": "weaponmaster_discipline", "type": "passive_notable", "unlock_rule": "adjacent", "connections": ["measured_guard", "parry_strike_1", "counterlord"], "cost": 1, "effects": {"parry": 5, "one_hand_damage": 5}, "ui_text": "Reward precise martial timing."},
		"parry_strike_1": {"name": "Parry Strike I", "region_id": "weaponmaster_discipline", "type": "active_unlock", "unlock_rule": "adjacent", "skill_family": "parry_strike", "skill_tier": 1, "connections": ["steel_timing"], "cost": 1, "effects": {"parry": 4, "melee_damage": 3}, "ui_text": "Unlock Parry Strike."},
		"counterlord": {"name": "Counterlord", "region_id": "weaponmaster_discipline", "type": "keystone", "unlock_rule": "adjacent", "connections": ["steel_timing"], "cost": 1, "effects": {"parry": 8, "block": -3}, "ui_text": "Turn defense into punishing counters."},
		"forward_pressure": {"name": "Forward Pressure", "region_id": "warpath_aggression", "type": "passive_notable", "unlock_rule": "adjacent", "connections": ["forward_step", "charge_1", "warpath_oath"], "cost": 1, "effects": {"run_speed": 3, "melee_damage": 4}, "ui_text": "Gain power through aggression."},
		"charge_1": {"name": "Charge", "region_id": "warpath_aggression", "type": "active_unlock", "unlock_rule": "adjacent", "skill_family": "charge", "skill_tier": 1, "connections": ["forward_pressure"], "cost": 1, "effects": {"run_speed": 2, "melee_damage": 3}, "ui_text": "Unlock Charge."},
		"warpath_oath": {"name": "Warpath Oath", "region_id": "warpath_aggression", "type": "keystone", "unlock_rule": "adjacent", "connections": ["forward_pressure"], "cost": 1, "effects": {"run_speed": 5, "attack_speed": 3, "block": -2}, "ui_text": "Push deeper into relentless aggression."}
	}
}
