extends RefCounted

const TREE := {
	"class_id": "mage",
	"start_node_id": "mage_start",
	"starter_active_family": "firebolt",
	"regions": [
		{"id": "start_core", "name": "Start / Core Mage", "theme": "Foundational spellcasting, mana, and defense", "node_ids": ["mage_start", "firebolt_1", "kindled_mind", "channeling_habit", "spell_thread", "arc_reservoir", "ashen_discipline", "scholars_skin", "awakened_mind", "scholarly_flow"], "cluster_ids": ["spark_of_thought", "initiates_circuit"], "entry_node_ids": ["mage_start"], "exit_node_ids": ["kindled_mind", "channeling_habit", "ashen_discipline"]},
		{"id": "ember_dominion", "name": "Ember Dominion", "theme": "Fire offense and destructive casting", "node_ids": ["scorching_insight", "firebolt_2", "flame_wave_1", "glass_invocation"], "cluster_ids": [], "entry_node_ids": ["kindled_mind"], "exit_node_ids": ["glass_invocation"]},
		{"id": "arcane_focus", "name": "Arcane Focus", "theme": "Spell cadence and mana flow", "node_ids": ["deep_wells", "quickened_thought", "arc_burst_1", "endless_current"], "cluster_ids": [], "entry_node_ids": ["channeling_habit", "spell_thread"], "exit_node_ids": ["endless_current"]},
		{"id": "frostbind_control", "name": "Frostbind Control", "theme": "Cold damage and control casting", "node_ids": ["winter_grip", "ice_shards_1", "frozen_mind"], "cluster_ids": [], "entry_node_ids": ["deep_wells"], "exit_node_ids": ["frozen_mind"]},
		{"id": "staff_battlemage", "name": "Staff Battlemage", "theme": "Sturdy arcane combat", "node_ids": ["runic_frame", "mana_shield", "spellsteel_oath"], "cluster_ids": [], "entry_node_ids": ["ashen_discipline", "scholars_skin"], "exit_node_ids": ["spellsteel_oath"]}
	],
	"clusters": [
		{"id": "spark_of_thought", "region_id": "start_core", "name": "Spark of Thought", "outer_node_ids": ["mage_start", "firebolt_1", "kindled_mind", "channeling_habit", "spell_thread", "arc_reservoir"], "center_node_id": "awakened_mind", "completion_rule": "all_outer_nodes"},
		{"id": "initiates_circuit", "region_id": "start_core", "name": "Initiate's Circuit", "outer_node_ids": ["mage_start", "spell_thread", "arc_reservoir", "ashen_discipline", "scholars_skin", "channeling_habit"], "center_node_id": "scholarly_flow", "completion_rule": "all_outer_nodes"}
	],
	"nodes": {
		"mage_start": {"name": "Mage Start", "region_id": "start_core", "type": "start", "unlock_rule": "always", "connections": ["kindled_mind", "channeling_habit", "spell_thread", "firebolt_1"], "cost": 0, "effects": {"intelligence": 1, "mana": 10}, "ui_text": "Begin as a Mage."},
		"firebolt_1": {"name": "Firebolt I", "region_id": "start_core", "type": "active_unlock", "unlock_rule": "adjacent", "skill_family": "firebolt", "skill_tier": 1, "connections": ["mage_start", "ashen_discipline"], "cost": 1, "effects": {"fire_damage": 4, "spell_damage": 3}, "ui_text": "Unlock Firebolt."},
		"kindled_mind": {"name": "Kindled Mind", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["mage_start", "scorching_insight", "awakened_mind"], "cost": 1, "effects": {"intelligence": 1}, "ui_text": "Gain Intelligence."},
		"channeling_habit": {"name": "Channeling Habit", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["mage_start", "deep_wells", "awakened_mind", "scholarly_flow"], "cost": 1, "effects": {"mana_regen": 4}, "ui_text": "Improve Mana Regeneration."},
		"spell_thread": {"name": "Spell Thread", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["mage_start", "arc_burst_1", "awakened_mind", "scholarly_flow"], "cost": 1, "effects": {"cast_speed": 2}, "ui_text": "Increase Cast Speed."},
		"arc_reservoir": {"name": "Arc Reservoir", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["ashen_discipline", "awakened_mind", "scholarly_flow"], "cost": 1, "effects": {"mana": 12}, "ui_text": "Increase Mana."},
		"ashen_discipline": {"name": "Ashen Discipline", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["firebolt_1", "arc_reservoir", "runic_frame", "scholarly_flow"], "cost": 1, "effects": {"staff_damage": 3, "wand_damage": 3}, "ui_text": "Improve wand and staff damage."},
		"scholars_skin": {"name": "Scholar's Skin", "region_id": "start_core", "type": "passive_minor", "unlock_rule": "adjacent", "connections": ["runic_frame", "scholarly_flow"], "cost": 1, "effects": {"stamina": 1, "max_health": 6}, "ui_text": "Gain Stamina and Health."},
		"awakened_mind": {"name": "Awakened Mind", "region_id": "start_core", "type": "cluster_center", "unlock_rule": "cluster_complete", "cluster_id": "spark_of_thought", "connections": [], "cost": 1, "effects": {"intelligence": 2, "spell_damage": 6, "mana_regen": 4}, "ui_text": "Unlock by completing the Spark of Thought ring."},
		"scholarly_flow": {"name": "Scholarly Flow", "region_id": "start_core", "type": "cluster_center", "unlock_rule": "cluster_complete", "cluster_id": "initiates_circuit", "connections": [], "cost": 1, "effects": {"cast_speed": 4, "mana": 16, "staff_damage": 4, "wand_damage": 4}, "ui_text": "Unlock by completing the Initiate's Circuit ring."},
		"scorching_insight": {"name": "Scorching Insight", "region_id": "ember_dominion", "type": "passive_notable", "unlock_rule": "adjacent", "connections": ["kindled_mind", "firebolt_2", "flame_wave_1"], "cost": 1, "effects": {"intelligence": 1, "fire_damage": 8}, "ui_text": "Strong firecasting power."},
		"firebolt_2": {"name": "Firebolt II", "region_id": "ember_dominion", "type": "active_upgrade", "unlock_rule": "adjacent", "skill_family": "firebolt", "skill_tier": 2, "connections": ["scorching_insight", "glass_invocation"], "cost": 1, "effects": {"fire_damage": 6, "cast_speed": 2}, "ui_text": "Upgrade Firebolt."},
		"flame_wave_1": {"name": "Flame Wave I", "region_id": "ember_dominion", "type": "active_unlock", "unlock_rule": "adjacent", "skill_family": "flame_wave", "skill_tier": 1, "connections": ["scorching_insight"], "cost": 1, "effects": {"fire_damage": 5, "spell_damage": 4}, "ui_text": "Unlock Flame Wave."},
		"glass_invocation": {"name": "Glass Invocation", "region_id": "ember_dominion", "type": "keystone", "unlock_rule": "adjacent", "connections": ["firebolt_2"], "cost": 1, "effects": {"spell_damage": 14, "fire_damage": 10, "defense": -4}, "ui_text": "Major fire damage with a defensive drawback."},
		"deep_wells": {"name": "Deep Wells", "region_id": "arcane_focus", "type": "passive_notable", "unlock_rule": "adjacent", "connections": ["channeling_habit", "quickened_thought", "arc_burst_1", "winter_grip"], "cost": 1, "effects": {"mana": 20, "mana_regen": 6}, "ui_text": "Expand your mana reserves."},
		"quickened_thought": {"name": "Quickened Thought", "region_id": "arcane_focus", "type": "passive_notable", "unlock_rule": "adjacent", "connections": ["deep_wells", "endless_current"], "cost": 1, "effects": {"cast_speed": 5, "spell_damage": 5}, "ui_text": "Cast faster and harder."},
		"arc_burst_1": {"name": "Arc Burst I", "region_id": "arcane_focus", "type": "active_unlock", "unlock_rule": "adjacent", "skill_family": "arc_burst", "skill_tier": 1, "connections": ["spell_thread", "deep_wells"], "cost": 1, "effects": {"spell_damage": 4, "cast_speed": 2}, "ui_text": "Unlock Arc Burst."},
		"endless_current": {"name": "Endless Current", "region_id": "arcane_focus", "type": "keystone", "unlock_rule": "adjacent", "connections": ["quickened_thought"], "cost": 1, "effects": {"mana_regen": 10, "cast_speed": 6, "spell_damage": -3}, "ui_text": "Cast faster with endless mana flow."},
		"winter_grip": {"name": "Winter Grip", "region_id": "frostbind_control", "type": "passive_notable", "unlock_rule": "adjacent", "connections": ["deep_wells", "ice_shards_1"], "cost": 1, "effects": {"cold_damage": 8, "mana": 8}, "ui_text": "Cold control and mana support."},
		"ice_shards_1": {"name": "Ice Shards I", "region_id": "frostbind_control", "type": "active_unlock", "unlock_rule": "adjacent", "skill_family": "ice_shards", "skill_tier": 1, "connections": ["winter_grip", "frozen_mind"], "cost": 1, "effects": {"cold_damage": 5, "spell_damage": 3}, "ui_text": "Unlock Ice Shards."},
		"frozen_mind": {"name": "Frozen Mind", "region_id": "frostbind_control", "type": "keystone", "unlock_rule": "adjacent", "connections": ["ice_shards_1"], "cost": 1, "effects": {"cold_damage": 12, "fire_damage": -4}, "ui_text": "Greatly improve cold power."},
		"runic_frame": {"name": "Runic Frame", "region_id": "staff_battlemage", "type": "passive_notable", "unlock_rule": "adjacent", "connections": ["ashen_discipline", "scholars_skin", "mana_shield"], "cost": 1, "effects": {"staff_damage": 6, "wand_damage": 6, "defense": 3}, "ui_text": "Shape sturdier spellcasting."},
		"mana_shield": {"name": "Mana Shield", "region_id": "staff_battlemage", "type": "active_unlock", "unlock_rule": "adjacent", "skill_family": "mana_shield", "skill_tier": 1, "connections": ["runic_frame", "spellsteel_oath"], "cost": 1, "effects": {"mana": 12, "defense": 4}, "ui_text": "Unlock Mana Shield."},
		"spellsteel_oath": {"name": "Spellsteel Oath", "region_id": "staff_battlemage", "type": "keystone", "unlock_rule": "adjacent", "connections": ["mana_shield"], "cost": 1, "effects": {"staff_damage": 10, "wand_damage": 10, "run_speed": -2}, "ui_text": "Commit to sturdier weapon-casting."}
	}
}
